import Header from "@swiftshop/components/Header/Header";
import "./globals.css";
import Footer from "@swiftshop/components/Footer/Footer";
import QueryClientProviders from "@swiftshop/lib/QueryClientProvider";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ToastContainerProvider from "@swiftshop/lib/ToastContainerProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryClientProviders>
          <Header />
          <ToastContainerProvider />
          {children}
          <Footer />
        </QueryClientProviders>
      </body>
    </html>
  );
}
