name: Swiftshop CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Create Deploy Branch
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          if git show-ref --verify --quiet "refs/heads/deploy/prod"; then
            echo "deploy/prod branch already exists, checking out and pushing to it"
            git checkout deploy/prod
            git merge main
            git push
          else
            echo "deploy/prod branch does not exist, creating and pushing to it"
            git checkout -b deploy/prod
            git push origin deploy/prod
          fi
